### PR TITLE
Ensure that tag are updated while running

### PR DESCRIPTION
**Pull request by pierresouchay**

### CODE REVIEW

**Comment by pierresouchay** [comment]
@ShimmerGlass @PHBourquin Already fixed in Consul 1.7.2 upstream (but comment misplaced, see https://github.com/hashicorp/consul/pull/7699 )

**Comment by pierresouchay** [comment]
@PHBourquin @ShimmerGlass Ok to merge this and build a new version?

**Comment by ShimmerGlass** [comment]
LGTM

**Comment by pierresouchay** [comment]
@PHBourquin Can you merge/tag to create a new version?

**Pull request merged**
